version: '3.8'
services:
  backend:
    build: .
    container_name: playlist-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/my-playlist-db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER} # <-- 환경 변수 사용
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD} # <-- 환경 변수 사용
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - YOUTUBE_PLAYLIST_ID=${YOUTUBE_PLAYLIST_ID}
  postgres-db:
    container_name: postgres-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER} # <-- 환경 변수 사용
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # <-- 환경 변수 사용